### PR TITLE
Align with PyTorch test_ops case suites

### PR DESCRIPTION
**Pull request by fengyuan14**
## Summary
This issue requests aligning the XPU test suite with PyTorch's test_ops case suites. It is a task/enhancement to ensure that XPU operator tests match the upstream PyTorch test_ops coverage and structure.

## Type
- **Category:** task
- **Platform:** xpu
- **Related Components:** test_ops, operator test suites

## Objective
Align the XPU test suite with PyTorch's test_ops case suites to ensure consistent coverage and structure with upstream PyTorch.

## Action Items
- [x] 🔍 Issue formatted (Discovery Agent)
  <details><summary>Discovery log</summary>
  
  **[2026-05-12 02:09:18]**
  **Summary:** This issue requests aligning the XPU test suite with PyTorch's test_ops case suites. It is a task/enhancement to ensure that XPU operator tests match the upstream PyTorch test_ops coverage and structure.
  **Failed tests:** N/A
  **Dependency:** N/A
  **Commit scope:** N/A
  **Tokens:** model: claude-sonnet-4 | tokens: 34.9K | in: 3 | out: 219 | cache_read: 32.9K | cache_write: 1.8K | cost: $0.0199
  
  </details>
- [ ] 🧠 Root cause identified (Triage Agent)
  <details><summary>Triage log</summary>
  
  </details>
- [ ] 🔧 Fix implemented (Fix Agent)
  <details><summary>Fix log</summary>
  
  </details>
- [ ] ✅ Fix verified locally
- [ ] 📋 PR proposed
- [ ] 👀 Human review
- [ ] 🎉 PR merged

## Original Issue
<details><summary>Original issue body</summary>

</details>

### CODE REVIEW

**Comment by EikanWang** [comment]
@fengyuan14 , please rebase this PR and refactor this test case by adding the implemented operations cases.

**Comment by fengyuan14** [comment]
image

**Comment by fengyuan14** [comment]
image

**Comment by fengyuan14** [comment]
@chuanqi129 will help to adjust preci script for new case directory `test/xpu`.

**Comment by chuanqi129** [comment]
> @chuanqi129 will help to adjust preci script for new case directory `test/xpu`.

Done, and change the pytorch from pined commit to latest nightly commit. cc: @EikanWang

**Review by chuanqi129 — APPROVED** [review]

**Pull request merged**
