### PR TITLE
Enhance Summary

### PR DESCRIPTION
**Pull request by RUIJIEZHONG66166**

### CODE REVIEW

**Review by chuanqi129 — APPROVED** [review]
Did we have a small scope test by using ondemand test workflow?

**Comment by RUIJIEZHONG66166** [comment]
The ondemand test results: https://github.com/intel/torch-xpu-ops/actions/runs/10109174514

**Comment by chuanqi129** [comment]
> The ondemand test results: https://github.com/intel/torch-xpu-ops/actions/runs/10109174514

Got it, thanks @RUIJIEZHONG66166. I have checked the summary excel file, overall LGTM, some comments with the summary format, take the you shared on-demand test as example,
1. Can we merge the different suite acc/perf summary sheets into one unite summary sheet?
2. Can we move the summary sheet as the first/default sheet of the excel file?

**Comment by RUIJIEZHONG66166** [comment]
> > The ondemand test results: https://github.com/intel/torch-xpu-ops/actions/runs/10109174514
> 
> Got it, thanks @RUIJIEZHONG66166. I have checked the summary excel file, overall LGTM, some comments with the summary format, take the you shared on-demand test as example,
> 
> 1. Can we merge the different suite acc/perf summary sheets into one unite summary sheet?
> 2. Can we move the summary sheet as the first/default sheet of the excel file?

Different suite of acc or perf can be merged into one acc or perf summary sheet as a enhancement later. 
Summary sheet needs the data of detail sheet when generating report. Its not suitable to move it as the first.

**Comment by fengyuan14** [comment]
Please wait for preci fixied.

**Pull request merged**
