### PR TITLE
Patching TEST_CUDA in PyTorch unit test to make cases work on XPU device

### PR DESCRIPTION
**Pull request by yuchengliu1**
Set `TEST_CUDA=True` in utils to enable more cuda case.
Rework test_nn&nn/test_pooling
port test_forseach&test_decomp

### CODE REVIEW

**Comment by fengyuan14** [comment]
Didn't you remove ut from run_test_with_only? And I see there are changes in test_nn and test_foreach. So you mean the change is for make the cases work on XPU? And originally, they are cuda bias?

**Comment by yuchengliu1** [comment]
> Didn't you remove ut from run_test_with_only? And I see there are changes in test_nn and test_foreach. So you mean the change is for making the cases work on XPU? And originally, they are cuda bias?

This PR have not done yet

**Comment by yuchengliu1** [comment]
`test_foreach` takes a long time to run, so test a white list of test_foreach in `run_test_with_only`. The full skip list of test_foreach.
https://github.com/intel/torch-xpu-ops/issues/469

**Comment by yuchengliu1** [comment]
`test_decomp` takes a long time to run, so test a white list of `test_comp` in `run_test_with_only`. The full skip list of `test_decomp` #470

**Comment by yuchengliu1** [comment]
P1 case in test_nn:
Related op is `col2im`
    "test_Fold_no_batch_dim_input_cuda",
    "test_Fold_no_batch_dim_int_input_cuda",

**Comment by fengyuan14** [comment]
Pleaes resolve the conflicts.

**Comment by yuchengliu1** [comment]
test_foreach only use 10min now. so move to run_test_with_skip

**Comment by fengyuan14** [comment]
Is it a new case?
image

**Comment by yuchengliu1** [comment]
> Is it a new case? image

This case passed in my local env. Something may changed in last code. Skip it now

**Review by fengyuan14 — APPROVED** [review]

**Pull request merged**
