### PR TITLE
Register groupnorm fallback

### PR DESCRIPTION
**Pull request by retonym**
Missing groupnorm forward fallback registration, causing nan in TIMM benchmark

### CODE REVIEW

**Comment by etaf** [comment]
Doese this op appeares only in forward? I used to collecte fallback ops in the training mode but missed this op.

**Comment by retonym** [comment]
> Doese this op appeares only in inference? I used to collecte fallback ops in the training mode and curious that I missed this op.

I find the this op in poolformer_m36 inference

**Comment by retonym** [comment]
@etaf @EikanWang Could we merge this pr

**Comment by retonym** [comment]
@EikanWang  could we merge this PR first to avoid TIMM accuracy issue in poolformer_m36 inference, before we implement such kernels.

**Review by etaf — APPROVED** [review]

**Pull request merged**
