### PR TITLE
Add boundary check for `embedding_bag` operator

### PR DESCRIPTION
**Pull request by chunhuanMeng**
Resolve issue: https://github.com/intel/torch-xpu-ops/issues/1052
Ref: https://github.com/pytorch/pytorch/blob/aaefa484417a84a2f5cfcfe4d5041b596c074b4c/aten/src/ATen/native/cuda/EmbeddingBag.cu#L89

### CODE REVIEW

**Comment by xytintel** [comment]
Does CUDA implement it?

**Comment by chunhuanMeng** [comment]
> Does CUDA implement it?

yes
Ref: https://github.com/pytorch/pytorch/blob/aaefa484417a84a2f5cfcfe4d5041b596c074b4c/aten/src/ATen/native/cuda/EmbeddingBag.cu#L83

**Comment by xytintel** [comment]
Does CUDA use any test cases to gate this change?

**Comment by chunhuanMeng** [comment]
> Does CUDA use any test cases to gate this change?
Not yet implemented
Ref：https://github.com/pytorch/pytorch/pull/96022

**Review by xytintel — APPROVED** [review]

**Pull request merged**
