### PR TITLE
Add aten::minimum/.out aten::maximum/.out

### PR DESCRIPTION
**Pull request by fengyuan14**
Add cases of test/test_binary_ufuncs.py to cover binary operators, which are not included in test_ops.py.

### CODE REVIEW

**Comment by fengyuan14** [comment]
maximum:
_test_ops.py::TestCommonXPU::test_dtypes__refs_maximum_xpu PASSED
_test_ops.py::TestCommonXPU::test_dtypes_maximum_xpu PASSED
_test_ops.py::TestCommonXPU::test_errors_maximum_xpu PASSED
_test_ops.py::TestCommonXPU::test_multiple_devices_maximum_xpu_float32 SKIPPED (fewer than 2 devices detected)
_test_ops.py::TestCommonXPU::test_multiple_devices_maximum_xpu_int64 SKIPPED (fewer than 2 devices detected)
_test_ops.py::TestCommonXPU::test_non_standard_bool_values_maximum_xpu_bool /home/sdp/miniconda3/envs/feng-upstream/lib/python3.9/site-packages/torch/testing/_comparison.py:1016: UserWarning: Aten Op fallback from XPU to CPU happends. This may have performance implications. If need debug the fallback ops please set environment variable `PYTORCH_DEBUG_XPU_FALLBACK=1`  (Triggered internally at /home/sdp/feng/project/pytorch/build/aten/src/ATen/RegisterXPU.cpp:2017.)
  if torch.all(matches):
PASSED
_test_ops.py::TestCommonXPU::test_noncontiguous_samples_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_noncontiguous_samples_maximum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_out__refs_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_out_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_out_requires_grad_error_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_out_warning__refs_maximum_xpu PASSED
_test_ops.py::TestCommonXPU::test_out_warning_maximum_xpu PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_maximum_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_errors__refs_maximum_xpu XFAIL
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_maximum_executor_aten_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_maximum_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_maximum_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_variant_consistency_eager_maximum_xpu_float32 PASSED

**Comment by fengyuan14** [comment]
Minimum:
_test_ops.py::TestCommonXPU::test_dtypes__refs_minimum_xpu PASSED
_test_ops.py::TestCommonXPU::test_dtypes_minimum_xpu PASSED
_test_ops.py::TestCommonXPU::test_errors_minimum_xpu PASSED
_test_ops.py::TestCommonXPU::test_multiple_devices_minimum_xpu_float32 SKIPPED (fewer than 2 devices detected)
_test_ops.py::TestCommonXPU::test_multiple_devices_minimum_xpu_int64 SKIPPED (fewer than 2 devices detected)
_test_ops.py::TestCommonXPU::test_non_standard_bool_values_minimum_xpu_bool /home/sdp/miniconda3/envs/feng-upstream/lib/python3.9/site-packages/torch/testing/_comparison.py:1016: UserWarning: Aten Op fallback from XPU to CPU happends. This may have performance implications. If need debug the fallback ops please set environment variable `PYTORCH_DEBUG_XPU_FALLBACK=1`  (Triggered internally at /home/sdp/feng/project/pytorch/build/aten/src/ATen/RegisterXPU.cpp:2017.)
  if torch.all(matches):
PASSED
_test_ops.py::TestCommonXPU::test_noncontiguous_samples_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_noncontiguous_samples_minimum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_out__refs_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_out_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_out_requires_grad_error_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_out_warning__refs_minimum_xpu PASSED
_test_ops.py::TestCommonXPU::test_out_warning_minimum_xpu PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref__refs_minimum_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_errors__refs_minimum_xpu XFAIL
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_executor__refs_minimum_executor_aten_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_meta__refs_minimum_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_bfloat16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_bool PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_float16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_float32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_float64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_int16 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_int32 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_int64 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_int8 PASSED
_test_ops.py::TestCommonXPU::test_python_ref_torch_fallback__refs_minimum_xpu_uint8 PASSED
_test_ops.py::TestCommonXPU::test_variant_consistency_eager_minimum_xpu_float32 PASSED

**Comment by fengyuan14** [comment]
Add test/test_binary_ufuncs cases. test_binary_ufuncs covers binary operators which are not included in test_ops. Here is evaluation of existing failures,
image

**Comment by fengyuan14** [comment]
test_binary_ufuncs:
image

**Comment by fengyuan14** [comment]
minimum in test_binary_ufuncs,
image
image
image
image
image
image
image
image
image
image
image
image

**Review by EikanWang — APPROVED** [review]

**Pull request merged**
